language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
before_install:
- chmod +x ./gradlew
- yes | sdkmanager "platforms;android-27"
script:
- "./gradlew build"

